[window]
padding = { x = 0, y = 0 }

[font]
normal = { family = "CaskaydiaCove Nerd Font Mono", style = "Normal" }
bold = { family = "CaskaydiaCove Nerd Font Mono", style = "Bold" }
italic = { family = "CaskaydiaCove Nerd Font Mono", style = "Italic" }
bold_italic = { family = "CaskaydiaCove Nerd Font Mono", style = "Bold Italic" }
size = 11

[cursor]
style = { shape = "Block", blinking = "On" }
vi_mode_style = { shape = "Beam", blinking = "On" }

[general]
live_config_reload = true
import = ["~/.config/alacritty/kanso_mist.toml"]
