# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
scan_timeout = 10

[directory]
truncation_length = 4
repo_root_style = "bold white"
repo_root_format = '[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) '

[aws]
disabled = true

[azure]
disabled = true

[gcloud]
disabled = true

[git_state]
format = "\\([$state( $progress_current/$progress_total)]($style)\\) "
disabled = false

[git_metrics]
disabled = false

[kubernetes]
disabled = false

[[kubernetes.contexts]]
context_pattern = "arn:aws:eks:[\\w-]+:(?P<account>\\d+):cluster/(?P<cluster>[\\w-]+)"
context_alias = "aws @ $account/$cluster"

[[kubernetes.contexts]]
context_pattern = "(?P<user>[\\w-]+)@(?P<cluster>.+?)-[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$"
context_alias = "scw @ $user/$cluster"


[[battery.display]]
threshold = 20
style = "bold red"
